### ISSUE TITLE
Allow sorting by price

### ISSUE THREAD

**Issue by bcus-y-not** [keeblabs/roadmap#11]
Please allow users to sort by price when viewing switches. Current sorting by A - Z and Z - A is not enough

**Comment by ryanskidmore** [comment]
100% agree, this is a must. We'll do this along with #12.

**Comment by ryanskidmore** [comment]
Hey @bcus-y-not, just a heads up that this is live now. Let us know what you think!

A couple of things worth mentioning:

**The price shown on the category/collection view doesn't include shipping**
We didn't think including this in the unit price would show a representative price per item, especially when some products (e.g. switches) are sold individually in packs of one. On the flipside, we also recognise that not including the shipping cost isn't representative of the per unit cost either. This is more of an issue with retailers who ship internationally, so we may add a filter at a later date to only show prices from suppliers in your country.

**Not every product will show a price**
We don't yet have retailer listings for every product, so not every product will have a price.

**The prices may be out of date**
We don't have fully up to date price data, so sometimes the data we hold might be stale. This is a more of a problem for quantities changing (i.e. a retailer changes the quantity from 10 to 1) but also applies to prices at a lesser degree.
